'use client'
import { useAppDispatch, useAppSelector } from '@/app/store'
import { decrementCounter, incrementCounter, initCounterState, resetCounter } from '@/app/store/counter/counterSlice'
import React, { useEffect, useState } from 'react'

/* interface Props{
    value: number
} */

// Generated by https://quicktype.io
export interface CounterRequest {
  method: string;
  count:  number;
}

const getAPICounter = async():Promise<CounterRequest> => {
  const data = await fetch('/api/counter')
  .then((res) => res.json())
  .catch((err) => console.log(err))

  return data;
}


export default function CartCounter(/* {value = 0}: Props */) {
  const counter = useAppSelector(state => state.counter.count)
  const dispatch = useAppDispatch()
  
  
  useEffect(() => {
    getAPICounter().then(({count}) => dispatch(initCounterState(count)))
  }, [dispatch])

  //useEffect(() => {
  //  dispatch(initCounterState(value))
 // }, [dispatch, value])
 // const [counter, setCounter] = useState(value)

 // const aumentCounter = () => {
 //  setCounter(counter + 1)
 // }

  //const decreaseCounter = () => {
  // if(counter === 0) {
  //   return ''
  // } else {
  //   setCounter(counter - 1)
  // }
  //}
  return (
    <>
    <span className='text-8xl'>{counter}</span>  
    <div className='flex'>
          <button /* onClick={aumentCounter} */ onClick={() => dispatch(incrementCounter())} className='flex items-center justify-center p-2 rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all mr-2 w-[100px]'>+</button>
          <button /* onClick={decreaseCounter} */ onClick={() => dispatch(decrementCounter())} className='flex items-center justify-center p-2 rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all mr-2 w-[100px]'>-</button>
        </div>
    </>
  )
}
